# KLUDGE: Enable the rules individually below for the time being
# to avoid being overwhelmed with errors.
default: false

MD001: true
MD003:
  style: atx
MD004:
  style: dash
MD005: true
MD007: true
MD009: true
MD010: true
MD011: true
MD012: true
MD041: true
