# Enable all rules
default: true

# Disable some rules
MD013: false
MD026: false
MD045: false
MD046: false

# Configure some rules
MD003:
  style: atx
MD004:
  style: dash
MD029:
  style: ordered
MD033:
  allowed_elements: [br]
MD044:
  names: [Javascript]
  code_blocks: false
MD048:
  style: backtick
MD049:
  style: underscore
MD050:
  style: asterisk
