INHERIT: ./nav.yaml
copyright: © 2022 Spacelift, Inc. All rights reserved
site_author: Spacelift
site_description: Collaborative Infrastructure For Modern Software Teams
site_name: Spacelift
theme:
  favicon: assets/images/favicon.png
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tracking
  font:
    text: Nunito Sans
  language: en
  logo: assets/images/logo.svg
  name: material
  palette:
    scheme: spacelift
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      auto_title: false
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: »
      permalink_title: Anchor link to this section
extra_css:
  - assets/css/extra.css
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/spaceliftio-103558488009736/
      name: Spacelift on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/spaceliftio
      name: Spacelift on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/spacelift-io/mycompany/
      name: Spacelift on LinkedIn
