site_name: Spacelift Documentation
theme:
  favicon: assets/favicon.ico
  language: en
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tracking
extra_css:
  - assets/css/extra.css
extra_javascript:
  - assets/javascript/extra.js
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      auto_title: false
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: »
      permalink_title: Anchor link to this section
plugins:
  - search:
      lang: en
extra:
  generator: false
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/spaceliftio-103558488009736/
      name: Spacelift on Facebook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/spaceliftio
      name: Spacelift on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/spacelift-io/mycompany/
      name: Spacelift on LinkedIn
nav:
  - Hello, Spacelift!: README.md
  - Getting started: getting-started.md
  - Main Concepts:
    - Stack:
      - concepts/stack/README.md
      - Creating a stack: concepts/stack/creating-a-stack.md
      - Stack settings: concepts/stack/stack-settings.md
      - Organizing stacks: concepts/stack/organizing-stacks.md
      - Stack locking: concepts/stack/stack-locking.md
      - Drift detection: concepts/stack/drift-detection.md
    - Configuration:
      - concepts/configuration/README.md
      - Environment: concepts/configuration/environment.md
      - Context: concepts/configuration/context.md
      - Runtime Configuration:
        - concepts/configuration/runtime-configuration/README.md
        - YAML reference: concepts/configuration/runtime-configuration/runtime-yaml-reference.md
    - Run:
      - concepts/run/README.md
      - Task: concepts/run/task.md
      - Proposed run (preview): concepts/run/proposed.md
      - Tracked run (deployment): concepts/run/tracked.md
      - Module test case: concepts/run/test-case.md
      - User-Provided Metadata: concepts/run/user-provided-metadata.md
    - Policy:
      - concepts/policy/README.md
      - Login policy: concepts/policy/login-policy.md
      - Access policy: concepts/policy/stack-access-policy.md
      - Approval policy: concepts/policy/approval-policy.md
      - Initialization policy: concepts/policy/run-initialization-policy.md
      - Plan policy: concepts/policy/terraform-plan-policy.md
      - Push policy: concepts/policy/git-push-policy.md
      - Task policy: concepts/policy/task-run-policy.md
      - Trigger policy: concepts/policy/trigger-policy.md
  - Resources: concepts/resources.md
  - Worker pools: concepts/worker-pools.md
  - VCS Agent Pools: concepts/vcs-agent-pools.md
